#!/bin/sh
# VoIP SIP Bridge - run.sh
# Reads HA options, generates Asterisk configs, starts Asterisk + bridge.

set -e

# ---------------------------------------------------------------------------
# Read HA options from /data/options.json
# ---------------------------------------------------------------------------
OPTIONS=/data/options.json

get_opt() {
    python3 -c "import json; d=json.load(open('$OPTIONS')); print(d.get('$1',''))"
}

get_opt_bool() {
    python3 -c "import json; d=json.load(open('$OPTIONS')); print(str(d.get('$1',False)).lower())"
}

get_opt_list() {
    python3 -c "import json; d=json.load(open('$OPTIONS')); print(' '.join(str(x) for x in d.get('$1',[])))"
}

VOIP_USER=$(get_opt voip_username)
VOIP_PASS=$(get_opt voip_password)
VOIP_DOMAIN=$(get_opt voip_domain)
VOIP_PROXY=$(get_opt voip_proxy)
VOIP_PORT=$(get_opt voip_port)
VOIP_TRANSPORT=$(get_opt voip_transport)
VOIP_SRTP=$(get_opt_bool voip_srtp)
VOIP_DID=$(get_opt did_number)
HA_URL=$(get_opt ha_url)
HA_TOKEN=$(get_opt ha_token)
ANTHROPIC_API_KEY=$(get_opt anthropic_api_key)
GROQ_API_KEY=$(get_opt groq_api_key)
OWNER_NAME=$(get_opt owner_name)
AVAILABILITY_INFO=$(get_opt availability_info)
AI_RECEPTIONIST=$(get_opt_bool ai_receptionist)
AUTO_ANSWER=$(get_opt_bool auto_answer)
PLAY_GREETING=$(get_opt_bool play_greeting)
GREETING_TEXT=$(get_opt greeting_text)
RECORD_CALLS=$(get_opt_bool record_calls)
VOIP_CODECS=$(get_opt_list voip_codecs)
AMI_SECRET=$(cat /proc/sys/kernel/random/uuid 2>/dev/null | tr -d '-' || echo "voipbridge$(date +%s)")
EXTERNAL_IP=$(get_opt external_ip)
[ -z "$EXTERNAL_IP" ] && EXTERNAL_IP=$(curl -s --max-time 3 https://api.ipify.org 2>/dev/null)
[ -z "$EXTERNAL_IP" ] && EXTERNAL_IP=$(curl -s --max-time 3 https://checkip.amazonaws.com 2>/dev/null)

# Defaults
[ -z "$VOIP_PORT" ] && VOIP_PORT=5060
[ -z "$VOIP_TRANSPORT" ] && VOIP_TRANSPORT=udp
[ -z "$VOIP_PROXY" ] && VOIP_PROXY="$VOIP_DOMAIN"
[ -z "$VOIP_CODECS" ] && VOIP_CODECS="opus ulaw alaw"
[ "$VOIP_SRTP" = "true" ] && VOIP_ENCRYPTION="sdes" || VOIP_ENCRYPTION="no"

# Validate
[ -z "$VOIP_USER" ] && echo "ERROR: voip_username required" && exit 1
[ -z "$VOIP_PASS" ] && echo "ERROR: voip_password required" && exit 1
[ -z "$HA_TOKEN" ]  && echo "ERROR: ha_token required" && exit 1

echo "VoIP SIP Bridge starting..."
echo "User: $VOIP_USER | Domain: $VOIP_DOMAIN | Proxy: $VOIP_PROXY | DID: $VOIP_DID"
echo "Transport: $VOIP_TRANSPORT:$VOIP_PORT | Codecs: $VOIP_CODECS"

export VOIP_USER VOIP_PASS VOIP_DOMAIN VOIP_PROXY VOIP_PORT VOIP_TRANSPORT
export VOIP_ENCRYPTION VOIP_CODECS VOIP_DID HA_URL HA_TOKEN
export AUTO_ANSWER PLAY_GREETING GREETING_TEXT RECORD_CALLS AMI_SECRET
export EXTERNAL_IP
export ANTHROPIC_API_KEY GROQ_API_KEY OWNER_NAME AVAILABILITY_INFO AI_RECEPTIONIST

# ---------------------------------------------------------------------------
# Generate dynamic Asterisk configs into /tmp/voip/
# These are #included by the static configs in /etc/asterisk/
# ---------------------------------------------------------------------------
mkdir -p /tmp/voip

python3 - << 'PYEOF'
import os

user       = os.environ['VOIP_USER']
password   = os.environ['VOIP_PASS']
domain     = os.environ['VOIP_DOMAIN']
proxy      = os.environ['VOIP_PROXY']
port       = os.environ.get('VOIP_PORT', '5060')
transport  = os.environ.get('VOIP_TRANSPORT', 'udp')
encryption = os.environ.get('VOIP_ENCRYPTION', 'no')
codecs     = os.environ.get('VOIP_CODECS', 'opus ulaw alaw').split()
ami_secret = os.environ['AMI_SECRET']
external_ip = os.environ.get("EXTERNAL_IP", "")

transport_name = f'transport-{transport}'
codec_lines    = '\n'.join(f'allow={c}' for c in codecs)

pjsip = f"""; pjsip_dynamic.conf - generated by run.sh

[{transport_name}]
type=transport
protocol={transport}
bind=0.0.0.0:{port}
external_signaling_address={external_ip}
external_media_address={external_ip}

[voip-auth]
type=auth
auth_type=userpass
username={user}
password={password}

[voip-aor]
type=aor
contact=sip:{domain}:{port}
qualify_frequency=30

[voip-reg]
type=registration
transport={transport_name}
outbound_auth=voip-auth
server_uri=sip:{domain}:{port}
client_uri=sip:{user}@{domain}
retry_interval=60
expiration=3600
outbound_proxy=sip:{proxy}:{port}

[voip]
type=endpoint
transport={transport_name}
context=incoming
disallow=all
{codec_lines}
outbound_auth=voip-auth
aors=voip-aor
from_user={user}
from_domain={domain}
direct_media=no
rtp_symmetric=yes
rewrite_contact=yes
force_rport=yes
trust_id_inbound=yes
send_pai=yes
dtmf_mode=rfc4733
media_encryption={encryption}

[voip-identify]
type=identify
endpoint=voip
match=199.87.144.0/24
match=199.87.145.0/24
"""

manager_user = f"""
[bridge]
secret={ami_secret}
deny=0.0.0.0/0.0.0.0
permit=127.0.0.1/255.255.255.0
read=all
write=all
"""

with open('/tmp/voip/pjsip_dynamic.conf', 'w') as f:
    f.write(pjsip)

with open('/tmp/voip/manager_dynamic.conf', 'w') as f:
    f.write(manager_user)

print('Generated /tmp/voip/pjsip_dynamic.conf')
print('Generated /tmp/voip/manager_dynamic.conf')
PYEOF

# ---------------------------------------------------------------------------
# Generate TTS greeting
# ---------------------------------------------------------------------------
if [ "$PLAY_GREETING" = "true" ]; then
    GREETING_WAV="/share/voip/greeting.wav"
    if [ ! -f "$GREETING_WAV" ]; then
        echo "Generating TTS greeting..."
        espeak -a 150 -s 130 -v en "$GREETING_TEXT" \
            --stdout | sox -t wav - -r 8000 -c 1 "$GREETING_WAV" 2>/dev/null \
            && echo "Greeting saved to $GREETING_WAV" \
            || echo "WARNING: espeak/sox failed - will use default Asterisk sounds"
    fi
fi

# ---------------------------------------------------------------------------
# Start Asterisk
# ---------------------------------------------------------------------------
echo "Starting Asterisk..."
asterisk -f -C /etc/asterisk/asterisk.conf &
ASTERISK_PID=$!

# Wait up to 20 seconds for Asterisk to be ready
for i in $(seq 1 20); do
    asterisk -rx "core show version" > /dev/null 2>&1 && echo "Asterisk is ready." && break
    sleep 1
done

# Reload PJSIP so it picks up the dynamic config we just wrote
echo "Reloading PJSIP..."
asterisk -rx "module reload res_pjsip.so" 2>&1 || true
sleep 2
asterisk -rx "pjsip show registrations" 2>&1 || true

# ---------------------------------------------------------------------------
# Install AGI handler
# ---------------------------------------------------------------------------
cp /opt/bridge/agi_handler.py /var/lib/asterisk/agi-bin/agi_handler.py 2>/dev/null || true
chmod +x /var/lib/asterisk/agi-bin/agi_handler.py 2>/dev/null || true

# ---------------------------------------------------------------------------
# Start AMI monitor and command API
# ---------------------------------------------------------------------------
echo "Starting AMI monitor..."
python3 /opt/bridge/ami_monitor.py \
    --ami-host 127.0.0.1 \
    --ami-port 5038 \
    --ami-secret "$AMI_SECRET" \
    --ha-url "$HA_URL" \
    --ha-token "$HA_TOKEN" &
AMI_PID=$!

echo "Starting command API on port 8089..."
python3 /opt/bridge/command_api.py \
    --ami-host 127.0.0.1 \
    --ami-port 5038 \
    --ami-secret "$AMI_SECRET" \
    --api-port 8089 &
API_PID=$!

echo "VoIP SIP Bridge is running."

# ---------------------------------------------------------------------------
# Monitor and restart children if they die
# ---------------------------------------------------------------------------
while true; do
    sleep 5
    if ! kill -0 "$AMI_PID" 2>/dev/null; then
        echo "AMI monitor died - restarting..."
        python3 /opt/bridge/ami_monitor.py \
            --ami-host 127.0.0.1 --ami-port 5038 --ami-secret "$AMI_SECRET" \
            --ha-url "$HA_URL" --ha-token "$HA_TOKEN" &
        AMI_PID=$!
    fi
    if ! kill -0 "$API_PID" 2>/dev/null; then
        echo "Command API died - restarting..."
        python3 /opt/bridge/command_api.py \
            --ami-host 127.0.0.1 --ami-port 5038 --ami-secret "$AMI_SECRET" \
            --api-port 8089 &
        API_PID=$!
    fi
    if ! kill -0 "$ASTERISK_PID" 2>/dev/null; then
        echo "FATAL: Asterisk exited - shutting down."
        exit 1
    fi
done
