[modules]
autoload=yes

noload => chan_alsa.so
noload => chan_console.so
noload => chan_mgcp.so
noload => chan_skinny.so
noload => chan_unistim.so
noload => chan_iax2.so
noload => app_festival.so
noload => res_calendar.so
noload => res_prometheus.so
noload => pbx_lua.so
noload => pbx_ael.so
noload => pbx_dundi.so
noload => app_amd.so
noload => app_voicemail_imap.so
noload => app_alarmreceiver.so
noload => app_queue.so
noload => res_phoneprov.so
noload => res_hep.so
noload => res_stun_monitor.so
